### ISSUE TITLE
Creating a custom map

### ISSUE THREAD

**Issue by timstallinger** [Reinisch/Warcraft-Arena-Unity#1]
Hey, first of all thank you so much for keeping this project going and working on it so much.
I was just going through the Unity project and tired to put custom maps in there. However, the character doesn't walk on any surface besides the arena. It doesn't fall through and you can blink over the surface but walking is impossible. Is it the Mesh, that makes the difference? And how can I avoid this problem?
Thank you in advance!

**Comment by Reinisch** [comment]
Try to set Ground layer for your custom map colliders, like in scene Lordaeron at World/Maps/Lordaeron Arena Map/Location/Lordaeron Arena/Arena.

**Comment by timstallinger** [comment]
Thank you very much! 👍 I am constantly following your repo and looking everyday, what you commited 😆 very nice project! Keep it up!
