### ISSUE TITLE
Creating discord channel for contribution

### ISSUE THREAD

**Issue by LuigiElleBalotta** [Reinisch/Warcraft-Arena-Unity#2]
I Suggest to create a discord channel for contributions, to create a community..
Also could be a good idea to implement a discord chat bot connected with the game :P

**Comment by Reinisch** [comment]
Alright I created discord channel, here it is https://discord.gg/d62a5zG

I have never created any chat bots, but I can add you and you can implement anything you want :)

**Comment by LuigiElleBalotta** [comment]
@Reinisch can you re-send me the invitation link? :D Btw i have not much time but i can see what can i do! It's been a lot of time i don't use unity

**Comment by Reinisch** [comment]
Do you mean discord or git repo link? It looks like you are already in.

**Comment by LuigiElleBalotta** [comment]
I mean discord :)

**Comment by Reinisch** [comment]
Does this link work for you? https://discord.gg/d62a5zG
