### ISSUE TITLE
[Networking] Offline scenes

### ISSUE THREAD

**Issue by LuigiElleBalotta** [Reinisch/Warcraft-Arena-Unity#3]
There can be a cool difference between scenes:
- Online Scenes (using bolt)
- Offline Scenes

Making 2 scenes (online & offline) instead of 1 means that there can be difference stories/status in the same map (example: Lordaeron).
Making 1 scene and play there with online/offline feature means that I can play with other players, make some things in the story and if i stop and play offline i can start from where i stopped

There should be a decision about this feature

**Comment by Reinisch** [comment]
Do you mean something like hideout or garrison where player starts in single player mode and from there he may join other server rooms?

Photon Bolt probably has single player mode, I may look into that later.
But if you want offline scene to persist it may be quite hard since Photon only supports one instance and all entities are tied to Photon, it may require quite a lot of work.

**Comment by LuigiElleBalotta** [comment]
I suggest to make photon as a module that you can choose to enable or not
to switch from offline and online

Il ven 25 ott 2019, 17:54 Reinisch <notifications@github.com> ha scritto:

**Comment by Reinisch** [comment]
Oh I get it, currently game relies completely on Photon States and Events.

Someone here https://forum.photonengine.com/discussion/12600/has-photon-bolt-an-offline-mode explains that Photon Bolt single mode does not require internet connection, so it will be easier to use Photon single mode then rewriting Core to support multiple networking solutions.

But anyway, maybe I rewrite it later, I wanted to try ECS when it will be ready.

**Comment by LuigiElleBalotta** [comment]
Got it, btw good work man :))

Il ven 25 ott 2019, 18:44 Reinisch <notifications@github.com> ha scritto:

**Comment by LuigiElleBalotta** [comment]
Bad news about this.. 
https://forum.unity.com/threads/offline-lan-with-photon-bolt.767642/#post-5123087

**Comment by Reinisch** [comment]
I just added offline mode in 3c627fd and it looks like it is working fine.
You can enter play mode and load map even without internet, but rooms in LAN won't work.

You still need internet to get session list, but if you manage to connect to other session in your local network then you will still have direct local connection.

**Comment by Reinisch** [comment]
Offline should work right now.
