### ISSUE TITLE
[Client, UI] Simple minimap

### ISSUE THREAD

**Issue by LuigiElleBalotta** [Reinisch/Warcraft-Arena-Unity#7]
Don't have any idea on how  to implement movable buttons in the minimap, by the way, since i'm still waking up (9 AM here) I remember i saw a video similar to [THIS](https://www.youtube.com/watch?v=faXQQ5b6GEs) that teaches how to implement a mini-map.
The right video is not the one that i liked, by the way i remember it was similar procedure..

**Comment by Reinisch** [comment]
Added basic minimap, a little bit different from what is in the video.

This one uses separate textures instead of original map.
